[[locations]]
names = ["the boonies", "boonies"]
tags = ["outside"]
description = "The middle of nowhere. It is heavily forested, filled with a labyrinth of trees, tangled branches, and hidden paths. The sound of unknown creatures rustling in the underbrush adds to the mystique of the place. The air is thick with the scent of pine, and the ground is soft with centuries of fallen leaves. A sense of isolation permeates this untamed wilderness."
appearance = "Heavily forested boonies."
exits = [
    { noun = "the forest", to = "Hubbleton Forest" },
]

[[locations]]
names = ["Hubbleton Forest", "forest", "woods"]
tags = ["outside"]
description = "A small forest at the far outskirts of town. Very little sunlight makes it through the dense tree cover. A light fog permeates the air, casting an ethereal glow over the twisted trees. The dark, quiet atmosphere is a bit unnerving, with shadows dancing and unknown creatures howling in the distance. Moisture clings to everything, and the faint sound of dripping water can be heard deep in the forest's core."
appearance = "Foggy, dense, creepy forest"
exits = [
    { noun = "ruined mansion", to = "ruined mansion entrance" },
]

[[locations]]
names = ["ruined mansion entrance"]
tags = ["outside", "ruined mansion"]
description = "An eerie entrance to a crumbling mansion, surrounded by wild, overgrown vegetation. The large wooden doors hang askew, creaking in the wind, inviting or warning those who dare to enter. Broken windows reveal glimpses of decay inside, and the rotting wood exudes a musty, forgotten smell. The remnants of grandeur are still visible, hinting at a mysterious past."
appearance = "Rural mansion in ruins, broken windows, rotting wood"
exits = [
    { preposition = "inside", to = "ruined mansion living room" },
    { preposition = "to", noun = "forest", to = "Hubbleton Forest" }
]

[[locations]]
names = ["ruined mansion living room"]
tags = ["inside", "ruined mansion"]
description = "A once-grand living room now consumed by nature. The wallpaper is peeling, chandeliers hang broken, and luxurious furnishings lay rotting. Plant overgrowth reaches in through the shattered windows, reclaiming the space as its own. Paintings of unknown figures watch silently from the walls, their faces obscured by time."
appearance = "A decayed, ruined cabin living room overgrown with plants"
exits = [
    { preposition = "outside", to = "ruined mansion entrance" },
    { preposition = "through", noun = "trapdoor", to = "secret bunker" },
]

[[locations]]
names = ["secret bunker"]
tags = ["inside", "ruined mansion"]
description = "A hidden underground bunker filled with mysterious treasures. This space is a stark contrast to the ruin above. The walls are lined with shelves filled with enigmatic artifacts, gleaming in the artificial light. A sense of timelessness pervades the room, as though the secrets within have waited years to be discovered."
appearance = "Secret bunker"
exits = [
    { preposition = "through", noun = "trapdoor", to = "ruined mansion living room" },
]

[[blocks]]
names = ["trapdoor"]
from = "ruined mansion living room"
to = "secret bunker"
one_way = false
description = "A large bronze padlock holds the trapdoor in place. It won't budge."
appearance = "Large metal trapdoor on wooden floor secured with large bronze padlock"