[[locations]]
names = ["Cave Entrance"]
tags = ["mountain", "cave"]
description = "The mouth of Turtle Cave opens before you, inviting you into its dark depths. The cave gets its name from the turtle-like shape of the rocks near the entrance. A slight chill emanates from within, and the sound of dripping water echoes through the air."
appearance = "Mountain cave entrance with turtle-shaped rocks."
exits = [
    { noun = "cave tunnel", to = "Cave Tunnel" },
]

[[locations]]
names = ["Cave Tunnel"]
tags = ["cave"]
description = "The tunnel leads deeper into the cave, the walls wet with moisture. Stalactites hang down like icicles, and you can hear the distant sound of water flowing."
appearance = "Damp cave tunnel with stalactites."
exits = [
    { noun = "glowing chamber", to = "Glowing Chamber" },
    { noun = "narrow passage", to = "Narrow Passage" },
]

[[locations]]
names = ["Glowing Chamber"]
tags = ["cave"]
description = "A chamber illuminated by glowing minerals embedded in the walls. The soft blue light casts a magical glow, revealing sparkling gemstones and intricate rock formations."
appearance = "Chamber with glowing minerals and gems."
exits = [
    { noun = "subterranean lake", to = "Subterranean Lake" },
]

[[locations]]
names = ["Narrow Passage"]
tags = ["cave"]
description = "A narrow passage that twists and turns, leading deeper into the cave. The walls close in, and you have to watch your step as you navigate through."
appearance = "Narrow and winding cave passage."
exits = [
    { noun = "fossil chamber", to = "Fossil Chamber" },
]

[[locations]]
names = ["Subterranean Lake", "cave lake"]
tags = ["cave"]
description = "A subterranean lake with crystal-clear water. The reflection of the glowing minerals dances on the water's surface, creating a surreal and breathtaking scene."
appearance = "Underground lake with clear water and glowing reflections."
exits = [
    { noun = "waterfall alcove", to = "Waterfall Alcove" },
]

[[locations]]
names = ["Waterfall Alcove"]
tags = ["cave"]
description = "An alcove with a small waterfall feeding into the lake. The sound of water cascading over rocks fills the space, and the air is fresh and cool."
appearance = "Alcove with a small waterfall in the cave."
exits = [
    { noun = "subterranean lake", to = "subterranean lake" },
]

[[locations]]
names = ["Fossil Chamber"]
tags = ["cave"]
description = "A chamber filled with ancient fossils embedded in the walls. The remnants of creatures from a bygone era tell a silent story of the earth's history."
appearance = "Chamber with visible fossils in the cave walls."
exits = [
    { noun = "hidden tunnel", to = "Hidden Tunnel" },
]

[[locations]]
names = ["Hidden Tunnel"]
tags = ["cave"]
description = "A hidden tunnel that leads to unknown parts of the cave. It's dark and foreboding, and you can't help but feel a sense of mystery and adventure as you venture forward."
appearance = "Dark and hidden tunnel in the cave."
exits = [
    { noun = "mystical chamber", to = "Mystical Chamber" },
]

[[locations]]
names = ["Mystical Chamber"]
tags = ["cave"]
description = "A mystical chamber filled with strange symbols and carvings. The air is charged with energy, and you can feel a connection to something ancient and powerful."
appearance = "Chamber with mystical symbols and carvings."
exits = [
    { noun = "hidden tunnel", to = "hidden tunnel" }
]
