[[locations]]
names = ["Hubbleton Forest entrance", "Hubbleton Forest", "forest", "woods"]
tags = ["outside"]
description = "A small forest at the far outskirts of town. Very little sunlight makes it through the dense tree cover. A light fog permeates the air, casting an ethereal glow over the twisted trees. The dark, quiet atmosphere is a bit unnerving. You hear the sounds of unknown creatures rustling in the underbrush. The air is thick with the scent of pine, and the ground is soft with centuries of fallen leaves. Moisture clings to everything, and the faint sound of dripping water can be heard deep in the forest's core. Somewhere in this forest is a ruined cabin."
appearance = "Foggy, dense, creepy forest"
    [[locations.exits]]
    noun = "canyon road"
    to = "canyon road"
    [[locations.exits]]
    preposition = "north"
    to = "Large Boulder"
    [[locations.exits]]
    preposition = "west"
    to = "Big Tree"
    [[locations.exits]]
    preposition = "south"
    to = "Little Waterfall"
    [[locations.exits]]
    noun = "ruined mansion"
    to = "ruined mansion entrance"
    hidden = true
    findable = false
    description = "You know the forest like the back of your hand. You follow a very specific path until you reach the ruined cabin without making a single wrong turn."

[[locations]]
names = ["Large Boulder"]
tags = ["outside"]
description = "A large boulder resting in the middle of a thicket. It's large enough that it would be difficult to climb to the top. It looks vaguely like a face, keeping watch over this section of the forest."
appearance = "large boulder in middle of thick forest"
exits = [
    { preposition = "north", to = "Large Boulder", description = "After a long walk, you come across a very familiar-looking boulder. You haven't changed direction this whole time, or so you thought. Have you been walking in circles?" },
    { preposition = "south", to = "hubbleton forest entrance" },
    { preposition = "east", to = "hubbleton forest entrance" },
    { preposition = "west", to = "big tree"}
]

[[locations]]
names = ["Muddy Pond"]
tags = ["outside"]
description = "A small pond barely larger than a puddle. The water is brown, murky, and covered in algae. Water-skeeter bugs dart over the surface of the water."
appearance = "small muddy pond in middle of thick forest."
exits = [
    { preposition = "north", to = "hubbleton forest entrance" },
    { preposition = "south", to = "hubbleton forest entrance" },
    { preposition = "east", to = "large boulder" },
    { preposition = "west", to = "big tree"}
]

[[locations]]
names = ["Big Tree"]
tags = ["outside"]
description = "A unsually large tree looming over a particularly dense region of Hubbleton Forest."
appearance = "Large tree in thick forest"
exits = [
    { preposition = "north", to = "hubbleton forest entrance" },
    { preposition = "south", to = "Little Waterfall" }, # correct path
    { preposition = "east", to = "hubbleton forest entrance" },
    { preposition = "west", to = "little waterfall"}
]

[[locations]]
names = ["Little Waterfall", "Waterfall"]
tags = ["outside"]
description = "A small stream running through the dirt, carving a miniature waterfall only a few inches tall."
appearance = "Small stream carving a little trench through a thick forest, with a small waterfall."
exits = [
    { preposition = "north", to = "hubbleton forest entrance" },
    { preposition = "south", to = "hubbleton forest entrance"},
    { preposition = "east", to = "Rotten Log" }, # correct path
    { preposition = "west", to = "muddy pond" }
]

[[locations]]
names = ["Rotten Log", "Log"]
tags = ["outside"]
description = "A large, decaying log covered in moss and mushrooms. An ant colony is living underneath the log, and several spiders are keeping them company."
appearance = "Rotten log in forest with mushrooms growing on it."
exits = [
    { preposition = "north", to = "Small Ravine" }, # correct path
    { preposition = "south", to = "muddy pond" },
    { preposition = "east", to = "hubbleton forest entrance" },
    { preposition = "west", to = "little waterfall" }
]
    [[locations.items]]
    names = ["ant", "ants"]
    tags = ["hidden"]
    description = "A large carpenter ant found in the forest in a test tube."
    appearance = "Large camponotus ant worker in test tube."

[[locations]]
names = ["Small Ravine", "Ravine"]
tags = ["outside"]
description = "A small ravine carves through the forest here. It may have once been a river, but it seems to have dried up."
appearance = "Dried up riverbed in forest, small ravine."
exits = [
    { preposition = "north", to = "muddy pond" },
    { preposition = "south", to = "rotten log" },
    { preposition = "east", to = "big tree" },
    { preposition = "west", to = "bramble patch" } # correct path
]

[[locations]]
names = ["Bramble Patch"]
tags = ["outside"]
description = "The trees are a bit less dense here, giving way to thick clusters of thorny bushes. It's difficult to walk without acculumating dozens of tiny scratches."
appearance = "Bramble patch in middle of thick forest."
exits = [
    { preposition = "north", to = "muddy pond" },
    { preposition = "south", to = "hubbleton forest entrance" },
    { preposition = "east", to = "small ravine" },
    { preposition = "west", to = "dark forest" } # correct path
]

[[locations]]
names = ["Dark Forest"]
tags = ["outside"]
description = "This part of the forest is especialy dark and foggy. You can only see about 10 feet in front of you. The trees seem to be changing places every time you look around. You have no idea which direction you came from."
appearance = "Thick, dark, foggy, creepy forest."
exits = [
    { preposition = "deeper", to = "ruined mansion entrance" }
]

[[locations]]
names = ["ruined mansion entrance"]
tags = ["outside", "ruined mansion"]
description = "An eerie entrance to a crumbling mansion, surrounded by wild, overgrown vegetation. The large wooden doors hang askew, creaking in the wind, inviting or warning those who dare to enter. Broken windows reveal glimpses of decay inside, and the rotting wood exudes a musty, forgotten smell."
appearance = "Rural mansion in ruins with broken windows and a rotting wooden porch"
exits = [
    { preposition = "inside", to = "ruined mansion living room" },
    { preposition = "to", noun = "forest entrance", to = "Hubbleton Forest" }
]

[[locations]]
names = ["ruined mansion living room"]
tags = ["inside", "ruined mansion"]
description = "A once-grand living room now consumed by nature. The wallpaper is peeling, chandeliers hang broken, and luxurious furnishings lay rotting. Plant overgrowth reaches in through the shattered windows, reclaiming the space as its own. Paintings of unknown figures watch silently from the walls, their faces obscured by time."
appearance = "A decayed, ruined cabin living room overgrown with plants"
exits = [
    { preposition = "outside", to = "ruined mansion entrance" },
    { preposition = "through", noun = "trapdoor", to = "secret bunker" },
]

[[locations]]
names = ["secret bunker"]
tags = ["inside", "ruined mansion"]
description = "A hidden underground bunker filled with mysterious treasures. This space is a stark contrast to the ruin above. The walls are lined with shelves filled with enigmatic artifacts, gleaming in the artificial light. A sense of timelessness pervades the room, as though the secrets within have waited years to be discovered."
appearance = "Secret bunker"
exits = [
    { preposition = "through", noun = "trapdoor", to = "ruined mansion living room" },
]

[[blocks]]
names = ["trapdoor"]
from = "ruined mansion living room"
to = "secret bunker"
one_way = false
description = "A large bronze padlock holds the trapdoor in place. It won't budge."
appearance = "Large metal trapdoor on wooden floor secured with large bronze padlock"