[[locations]]
names = ["Kepler City Entrance", "city entrance"]
tags = ["outside"]
description = "The grand entrance to Kepler City, marked by a towering arch and bustling with activity. Skyscrapers loom in the distance, and the air is filled with the sounds of urban life."
appearance = "Busy city entrance with an impressive arch, cars, and pedestrians."
exits = [
    { noun = "main avenue", to = "main avenue" },
    { noun = "bus station", to = "bus station" },
]

[[locations]]
names = ["main avenue", "main ave"]
tags = ["outside"]
description = "The vibrant heart of Kepler City, Main Avenue is lined with shops, cafes, and street vendors. People bustle about, and the scent of food, coffee, and city air mingles together."
appearance = "Wide city avenue with shops, cafes, and crowds of people."
exits = [
    { noun = "city entrance", to = "city entrance" },
    { noun = "Ross Welford's street", to = "Welford street" },
]

[[locations]]
names = ["Welford street", "Ross Welford's street"]
tags = ["outside"]
description = "A quieter residential street just off Main Avenue. The homes here are well-kept, with small gardens. Ross Welford's house, known for its unique blue door, stands at the end of the street."
appearance = "Residential street with charming houses and gardens."
exits = [
    { noun = "main avenue", to = "main avenue" },
    { noun = "Ross Welford's house", to = "Ross Welford's house" },
]

[[locations]]
names = ["Ross Welford's house", "Welford's house"]
tags = ["inside"]
description = "The home of Ross Welford, filled with shelves of books, artifacts, and odd trinkets. The atmosphere is cozy, and the smell of old paper and wood fills the room. Ross can often be found in his study, deep in thought."
appearance = "Cozy home filled with books, artifacts, and a sense of history."
exits = [
    { preposition = "outside", to = "Welford street" },
]

[[locations]]
names = ["bus station", "Kepler City bus station"]
tags = ["outside"]
description = "The Kepler City Bus Station serves as a hub for travelers. Buses arrive and depart for various destinations, including Hubbleton. The station is filled with a mix of locals and tourists, all with their unique stories."
appearance = "Busy bus station with ticket booths, waiting areas, and buses coming and going."
exits = [
    { noun = "city entrance", to = "city entrance" },
]

[[locations]]
names = ["Kepler Park", "city park"]
tags = ["outside"]
description = "Kepler Park is a lush oasis in the heart of the city, filled with trees, ponds, and walking paths. It's a popular spot for relaxation, picnics, and enjoying nature amidst the urban landscape."
appearance = "Beautiful city park with trees, ponds, and people enjoying leisure activities."
exits = [
    { noun = "main avenue", to = "main avenue" },
]
