[[locations]]
names = ["Drain Entryway"]
tags = ["underground"]
description = "The entrance to the mysterious storm drain system of Hubbleton. Pipes line the walls in every direction."
appearance = "Dark and damp entryway to a city sewer system, manhole overhead, pipes along walls.."
exits = [
    { preposition = "up", to = "apartment complex" },
    { noun = "twisted corridor", to = "twisted corridor" },
]

[[locations]]
names = ["Twisted Corridor"]
tags = ["underground"]
description = "A twisting corridor filled with echoes."
appearance = "Damp, twisting corridor."
exits = [
    { noun = "drain junction", to = "drain junction" },
]

[[locations]]
names = ["Drain Junction"]
tags = ["underground"]
description = "A junction where the drain paths divide."
appearance = "A junction with various tunnels leading in different directions."
exits = [
    { preposition = "up", to = "center street" },
    { noun = "hidden path", to = "hidden path" },
]

[[locations]]
names = ["Hidden Path"]
tags = ["underground"]
description = "A hidden path that leads further into the darkness."
appearance = "Narrow hidden path filled with shadows."
exits = [
    { noun = "silent chamber", to = "silent chamber" },
]

[[locations]]
names = ["Silent Chamber"]
tags = ["underground"]
description = "A silent chamber filled with the echoes of the town's history."
appearance = "Silent and damp chamber."
exits = [
    { preposition = "up", to = "main street" },
    { noun = "forgotten passage", to = "forgotten passage" },
]

[[locations]]
names = ["Forgotten Passage"]
tags = ["underground"]
description = "A narrow forgotten passage filled with remnants of the past."
appearance = "Narrow, forgotten passage leading deeper into the unknown."
exits = [
    { noun = "deep junction", to = "deep junction" },
]

[[locations]]
names = ["Deep Junction"]
tags = ["underground"]
description = "A deep junction where several tunnels meet."
appearance = "Deep underground junction with many paths."
exits = [
    { preposition = "up", to = "high school entrance" },
    { noun = "shadowy corridor", to = "shadowy corridor" },
]

[[locations]]
names = ["Shadowy Corridor"]
tags = ["underground"]
description = "A corridor filled with shadows and whispers of the unknown."
appearance = "Dark, shadowy corridor."
exits = [
    { noun = "final chamber", to = "final chamber" },
]

[[locations]]
names = ["Final Chamber"]
tags = ["underground"]
description = "The final chamber of the storm drain, filled with silence and mystery."
appearance = "Final underground chamber filled with silence."
exits = [
    { preposition = "up", to = "gas station exterior" },
]
