[[topics]]
name = "Ghosts"
description = """

"""
leads_to = [] # this topic represents the aggregate of all the others

[[topics]]
name = "Alien SOS Signal"
description = """

"""
leads_to = [
    "Alien SOS Translation"
]

[[topics]]
name = "Alien SOS Translation"
description = """
Shortly before going extinct, the aliens known as the Ghosts sent out a series of SOS messages across the galaxy.
These messages describe a hostile takeover of their home star system by a rogue superintelligence of their own creation.
"""

[[topics]]
name = "Ghost Cipher"
description = """

"""

[[topics]]
name = "Ghost Homeworld"
description = """

"""

[[topics]]
name = "Ghost Singularity"
description = """

"""

[[topics]]
name = "Ghost Survivors"
description = """

"""

[[topics]]
name = "Ghost Transmission Zeta"
description = """

"""