# Generated by Django 4.2.2 on 2023-06-10 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('attack', models.IntegerField(blank=True, null=True)),
                ('nutrition', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'species',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('traversal_type', models.CharField(choices=[('Unbounded', 'Unbounded'), ('Connections Only', 'Connections Only')], max_length=20)),
                ('meters_per_unit', models.FloatField(default=1)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_maps', to='game.location')),
            ],
        ),
        migrations.CreateModel(
            name='LocationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_distance', models.FloatField(blank=True, null=True)),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_locations', to='game.location')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_locations', to='game.location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_locations', to='game.map'),
        ),
        migrations.CreateModel(
            name='ItemInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='game.item')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='game.location'),
        ),
        migrations.AddField(
            model_name='character',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='game.species'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
