# Generated by Django 4.2.2 on 2023-06-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='npc',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='world',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='item',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='item',
            name='defense',
        ),
        migrations.AddField(
            model_name='item',
            name='readable_message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Readable',
        ),
    ]
