# Generated by Django 4.2.2 on 2023-06-16 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='appearance',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='personality',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='world',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='capacity',
            field=models.PositiveIntegerField(default=10.0),
        ),
        migrations.AlterField(
            model_name='item',
            name='attack',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='defense',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='healing',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='magic_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='killable',
            name='hp',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='killable',
            name='max_hp',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='magicwielder',
            name='max_mp',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='magicwielder',
            name='mp',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='readable',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
