# Generated by Django 4.2.2 on 2023-06-10 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locationconnection',
            unique_together={('location_from', 'location_to')},
        ),
    ]
