# Generated by Django 4.2.2 on 2023-06-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_locationconnection_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='iteminstance',
            unique_together={('item', 'owner')},
        ),
    ]
