# Generated by Django 4.2.2 on 2023-06-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_area_options_alter_character_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacontext',
            name='relationship',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itemcontext',
            name='relationship',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='locationcontext',
            name='relationship',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='npccontext',
            name='relationship',
            field=models.TextField(blank=True),
        ),
    ]
