# Generated by Django 4.2.2 on 2023-07-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_entity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='path',
        ),
        migrations.AddField(
            model_name='block',
            name='paths',
            field=models.ManyToManyField(to='game.path'),
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(blank=True, choices=[('house', 'house'), ('store', 'store'), ('secret', 'secret'), ('other', 'other')], max_length=20),
        ),
    ]
