# Generated by Django 4.2.2 on 2023-06-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_location_appearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='npcprefab',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('nonbinary', 'nonbinary')], default='M', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('nonbinary', 'nonbinary')], default='M', max_length=16),
            preserve_default=False,
        ),
    ]
