# Generated by Django 4.2.2 on 2023-06-10 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_iteminstance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstance',
            name='carried',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='dropped_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.location'),
        ),
        migrations.AlterField(
            model_name='map',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_maps', to='game.location'),
        ),
    ]
