# Generated by Django 4.2.2 on 2023-06-24 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_traits_playertraits_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npcinstance',
            old_name='traits',
            new_name='prefab',
        ),
    ]
