# Generated by Django 4.2.2 on 2023-06-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_npcprefab_gender_player_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='npcprefab',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, choices=[('house', 'house'), ('store', 'store')], max_length=20),
        ),
        migrations.AddField(
            model_name='npcprefab',
            name='owned_locations',
            field=models.ManyToManyField(to='game.location'),
        ),
    ]
