# Generated by Django 4.2.2 on 2023-06-10 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_iteminstance_carried_iteminstance_dropped_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminstance',
            name='dropped_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.location'),
        ),
    ]
