# Generated by Django 4.2.2 on 2023-06-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_npcprefab_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcprefab',
            name='owned_locations',
            field=models.ManyToManyField(blank=True, to='game.location'),
        ),
    ]
