# Generated by Django 4.2.2 on 2023-06-27 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_npcprefab_owned_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerinstance',
            name='base',
        ),
        migrations.AddField(
            model_name='player',
            name='instance',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prefab', to='game.playerinstance'),
            preserve_default=False,
        ),
    ]
