# Generated by Django 4.2.2 on 2023-07-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_character_created_at_characterlog_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
