# Generated by Django 4.2.2 on 2023-07-28 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_block_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='previous_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_positionset', to='game.location'),
        ),
    ]
