# Generated by Django 4.2.2 on 2023-06-27 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_scheduleitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleitem',
            name='character',
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='npc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.npcprefab'),
            preserve_default=False,
        ),
    ]
