# Generated by Django 4.2.2 on 2023-07-29 12:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_character_previous_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9\\s\\']*$", 'Only alphanumeric characters, spaces and single quotes are allowed.')])),
            ],
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='location',
            name='interior',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='slug',
        ),
        migrations.AddField(
            model_name='entity',
            name='tags',
            field=models.ManyToManyField(to='game.tag'),
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9\\s\\']*$", 'Only alphanumeric characters, spaces and single quotes are allowed.')])),
                ('slug', models.SlugField(blank=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='game.entity')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='game.world')),
            ],
            options={
                'ordering': ['entity', 'name'],
                'unique_together': {('world', 'slug')},
            },
        ),
    ]
