# Generated by Django 4.2.2 on 2023-07-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_entity_appearance_alter_entity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='appearance',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
