# Generated by Django 4.2.2 on 2023-07-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_path_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='noun_slug',
            field=models.SlugField(default='1', max_length=20),
            preserve_default=False,
        ),
    ]
