# Generated by Django 4.2.2 on 2023-08-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_path_noun_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
