# Generated by Django 4.2.2 on 2023-08-09 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_rename_result_characterlog_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='previous_position',
        ),
        migrations.AddField(
            model_name='character',
            name='path_taken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.path'),
        ),
    ]
