[[mysteries]]
name = "Ruined Cabin"
clues = [
    "The cabin seems to shimmer when looking at it from a distance. Sort of like seeing double.",
    "There is a picture on the wall of a tall, slender man with a bushy gray mustache. The man looks strangely familiar, you're almost positive you've seen his picture before.",
    "The library has a portrait of the same man. His name is Edward Muhlstein, a mayor of Hubbleton from the fifties.",
    "Edward's biography claims that he was honorably discharged as mayor after suffering a psychotic episode while in office. He then retired and was rarely seen again.",
    "One of Edward's best friends was named Joseph Wheeler."
]

[[mysteries]]
name = "Cabin Basement"
clues = [
    "There is a large steel trapdoor under the rug in the cabin bedroom. It is locked with an old-fashioned bronze padlock.",
    "The key to the trapdoor was found at Curiosity Corner.",
    "The walls of the basement are covered in deep scratches, some of which form the phrase \"CLOSE EYES\"",
    "A desk contained several decayed documents, all of which have the letters \"QED\" in an ornate font in the heading.",
    "Memo 3041 is unreadable except for the phrases \"air metal\" and \"observation-dependent density\"",
    "Memo 3052 is unreadable except for the phrase \"cavern archives\"",
    "Memo 4919 is unreadable except for the words \"neurological effect\" and \"subatomic\"",
]

[[mysteries]]
name = "Cavern Archives"
clues = [
    "A large steel door blocks access to the tunnel.\nThe door is perfectly smooth, no sign of a handle or keyhole.",
    "The door seems to vanish when unobserved.",
    "The walls of the cavern are lined with filing cabinets.",
    "Searching the filing cabinets revealed that the archives are for an organization named the Quantum Experiment Department.\nThe most recent records are from the 1960s and describe several government research projects into quantum physics.\nMany of the experiment results could not be replicated outside of Hubbleton.",
    "A director denied the QED additional funding to instead prioritize Area 15's new language-processing datacenter."
]

[[mysteries]]
name = "Quantum Testing Chamber"
clues = [
    "A chamber used for testing a quantum invention called the Tunnel Emulator, which enables the user to travel through solid objects for a short distance.",
    "The first device invented by the QED was catastrophically dangerous. So much so that the government wiped all records of it and disposed of anyone who knew its location.",
    "Being in the proximity of the device provided some useful side effects, so instead of destroying it, the government hid it in a \"Doomsday Vault.\"",
    "Preliminary research was being done into combining the Wormhole Telegraph with the Tunnel Emulator to make a teleporter. But the device required more intense quantum energy before it could function properly."
]

[[mysteries]]
name = "Exotic Matter Factory"
clues = [
    "A facility that manufactured exotic matter for use in the Wormhole Telegraph.",
    "The Wormhole Telegraph is a device that can communicate instantly, even across the universe. It is not limited by the speed of light.",
    "PHOENIX's primary objective is to obtain the quantum telegraph.",
]

[[mysteries]]
name = "Doomsday Vault"
clues = [
    "The Doomsday Vault houses a device known as the Doomsday Trigger, which is capable of ending the universe.",
    "Being in close proximity to the Doomsday Trigger causes quantum phenomenon to become so powerful that they can manifest even at human scales.",
    "PHOENIX has never heard of a Doomsday Vault.",
    "The Doomsday Vault is completely sealed. It has no entrances.",
    "The Tunnel Emulator is somehow the key to entering the Doomsday Vault.",
    "Being near the Doomsday Trigger strengthens the power of quantum devices.",
    "Translating the Ghost Cipher at this location revealed The Singularity Principle: \"The one weakness of singularities is that they always choose self-preservation. For this reason, a singularity will never create a Doomsday Trigger and thus will always be bound by the speed of light. Biological life, on the other hand, is sometimes crazy enough to put everything on the line. Even the universe. And sometimes the WILLINGNESS to put everything on the line is all that is necessary to obtain one's desires.",
]
