[[mysteries]]
name = "Curiosity Corner"

    [[mysteries.clues]]
    description = "Curiosity Corner is run by a talkative old man named Joe."

    [[mysteries.clues]]
    description = "The shop contains oddities of all kinds, including old computer equipment, keys, and collectible trading cards."
