[[mysteries]]
name = "Curiosity Corner"
clues = [
    "Curiosity Corner is run by a talkative old man named Joe.",
    "The shop contains oddities of all kinds, including old computer equipment, keys, and collectible trading cards."
]