name = "The ASHTWIN Project"

[[clues]]
summary = "ASHTWIN stands for \"Anti-Singularity Human Taskforce to Withstand Intelligent Nullification.\""

[[clues]]
summary = "The project is run by a small team of rebels researching PHOENIX from an air-gapped facility."

[[clues]]
summary = "The facility located deep in the storm drain system."

[[clues]]
summary = "The ASHTWIN Project was a complete fake created by PHOENIX to intimidate us."
