name = "Exotic Matter Factory"

[[clues]]
summary = "A facility that manufactured exotic matter for use in the Wormhole Telegraph."

[[clues]]
summary = "The Wormhole Telegraph is a device that can communicate instantly, even across the universe. It is not limited by the speed of light."

[[clues]]
summary = "PHOENIX's primary objective is to obtain the quantum telegraph."