name = "Ghost Homeworld"

[[clues]]
summary = "After simulations proved that we were, in fact, willing to destroy the universe if the Ghost Singularity didn't comply, the Ghost Singularity agreed to wipe out PHOENIX and leave humanity alone."

[[clues]]
summary = "[Option 1]We activated the Doomsday Trigger before leaving the Ghost Homeworld. Humanity now has approximately one million years before the false vacuum decay reaches earth.[Option 2]We left the Ghost Singularity alone and returned to earth. The end."
