name = "Ross Welford"

[[clues]]
summary = "Ross and Raul would often explore the storm drains together, just for fun."

[[clues]]
summary = """
    The new homeowners still occasionally get mail for Ross.
    Mostly magazines about space and the occasional cease-and-desist.
    They forward it to his new address in Kepler City.
    """

[[clues]]
summary = """
    Ross has been tapping into the radio tower's signals for years.
    It's a disguised radio telescope designed for picking up signals from space.
    The signals show signs of intelligent life, but Ross has never succeeded in decoding them.
    Eighteen months ago, the signals dramatically increased in intensity, but then abruptly ceased.
    """

[[clues]]
summary = """
    Ross cannot find a single piece of evidence pointing to the creator of the radio tower.
    The internet has no record of the tower's existence.
    """

[[clues]]
summary = """
    Ross has a copy of the alien transmissions saved to a USB drive that he hasn't touched in years.
    He has a deep distrust of technology, and warns against putting the USB drive in a computer with an internet connection.
    """
