[[characters]]
names = ["Joe"]
personality = "A quirky, kind, wise old man who enjoys begin cryptic and mysterious."
description = "An old man who owns Curiosity Corner."
position = "Curiosity Corner"